# Generated by Django 3.0.5 on 2020-04-17 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('host_management', '0020_auto_20180801_1016'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='区域名称')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='入库时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, '正常'), (0, '停用')], verbose_name='状态')),
                ('add_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area_add_user', to=settings.AUTH_USER_MODEL, verbose_name='添加人')),
                ('update_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area_update_user', to=settings.AUTH_USER_MODEL, verbose_name='修改人')),
            ],
            options={
                'verbose_name': '区域',
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='区域名称')),
                ('supplier', models.CharField(max_length=30, verbose_name='供应商')),
                ('type', models.CharField(max_length=30, verbose_name='型号')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='入库时间')),
                ('manufacturing_date', models.DateField(verbose_name='生产时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, '正常'), (0, '停用'), (2, '迁出'), (4, '报废')], verbose_name='状态')),
                ('ID_fixed_assets', models.CharField(max_length=20, verbose_name='固定资产编号')),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='描述')),
                ('add_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_add_user', to=settings.AUTH_USER_MODEL, verbose_name='添加人')),
                ('area', models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.CASCADE, related_name='area_machine', to='host_management.Area', verbose_name='区域名称')),
                ('update_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_update_user', to=settings.AUTH_USER_MODEL, verbose_name='修改人')),
            ],
            options={
                'verbose_name': '设备',
            },
        ),
    ]
