# Generated by Django 3.0.5 on 2020-04-17 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host_management', '0021_area_machine'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='desc',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='描述'),
        ),
    ]
