# Generated by Django 3.0.5 on 2020-04-18 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('host_management', '0023_auto_20200417_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='operator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operator_user', to=settings.AUTH_USER_MODEL, verbose_name='操作人员'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='manufacturing_date',
            field=models.DateTimeField(verbose_name='生产时间'),
        ),
    ]
