# Generated by Django 3.0.5 on 2020-04-18 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('host_management', '0024_auto_20200418_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='update_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='update_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='machine_update_user', to=settings.AUTH_USER_MODEL, verbose_name='修改人'),
        ),
    ]
