# Generated by Django 3.0.5 on 2020-04-19 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('host_management', '0025_auto_20200418_1704'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'verbose_name': '区域', 'verbose_name_plural': '区域'},
        ),
        migrations.AlterModelOptions(
            name='machine',
            options={'verbose_name': '设备', 'verbose_name_plural': '设备'},
        ),
    ]
