# Generated by Django 3.0.5 on 2020-04-20 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('host_management', '0026_auto_20200419_0819'),
        ('task_pool', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TroubleTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='分类名称')),
            ],
            options={
                'verbose_name': '故障标签表',
                'verbose_name_plural': '故障标签表',
            },
        ),
        migrations.CreateModel(
            name='TroubleRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='平台名称')),
                ('event', models.CharField(max_length=50, verbose_name='事件和原因')),
                ('event_time', models.DateTimeField(verbose_name='故障时间')),
                ('handle_way', models.CharField(max_length=100, verbose_name='处理办法')),
                ('handle_time', models.DateTimeField(verbose_name='处理时间')),
                ('handle_result', models.PositiveSmallIntegerField(choices=[(1, '已处理'), (2, '未处理'), (3, '其它')], default=1, verbose_name='处理结果')),
                ('desc', models.CharField(blank=True, max_length=100, null=True, verbose_name='备注')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, '关闭'), (1, '开启')], default=1, verbose_name='状态')),
                ('handle_user', models.ManyToManyField(related_name='Trouble_user', to=settings.AUTH_USER_MODEL, verbose_name='处理人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tr_project1', to='host_management.ProjectInfo', verbose_name='项目')),
                ('tags', models.ManyToManyField(to='task_pool.TroubleTag', verbose_name='标签')),
                ('url', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tr_url1', to='host_management.DomainNameResolveInfo', verbose_name='域名')),
            ],
            options={
                'verbose_name': '故障表',
                'verbose_name_plural': '故障表',
            },
        ),
        migrations.CreateModel(
            name='InspectionTaskList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=20, null=True, verbose_name='创建人')),
                ('location', models.CharField(max_length=20, null=True, verbose_name='检查点')),
                ('create_time', models.DateTimeField(null=True, verbose_name='创建时间')),
                ('cycle', models.SmallIntegerField(null=True, verbose_name='任务生成周期')),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='检查内容描述')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_machine_name_list', to='host_management.Machine', verbose_name='巡检设备')),
                ('machine_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_machine_area_list_name', to='host_management.Machine', verbose_name='设备所在区域')),
                ('operator1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspection_list_operator1', to=settings.AUTH_USER_MODEL, verbose_name='负责人1')),
                ('operator2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspection_list_operator2', to=settings.AUTH_USER_MODEL, verbose_name='负责人2')),
            ],
            options={
                'verbose_name': '巡检任务表',
                'verbose_name_plural': '巡检任务表',
            },
        ),
        migrations.CreateModel(
            name='InspectionTaskCycleSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=20, null=True, verbose_name='检查点')),
                ('start_time', models.DateTimeField(null=True, verbose_name='起始时间')),
                ('cycle', models.SmallIntegerField(null=True, verbose_name='任务生成周期')),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='检查内容描述')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_machine_name', to='host_management.Machine', verbose_name='巡检设备')),
                ('machine_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_machine_area_name', to='host_management.Machine', verbose_name='设备所在区域')),
                ('operator1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_operator1', to=settings.AUTH_USER_MODEL, verbose_name='负责人1')),
                ('operator2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspection_operator2', to=settings.AUTH_USER_MODEL, verbose_name='负责人2')),
            ],
            options={
                'verbose_name': '巡检任务周期设定表',
                'verbose_name_plural': '巡检任务周期设定表',
            },
        ),
    ]
