# Generated by Django 3.0.5 on 2020-04-20 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_pool', '0003_auto_20200420_1947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inspectiontaskcyclesetting',
            old_name='machine_area',
            new_name='area',
        ),
        migrations.RenameField(
            model_name='inspectiontasklist',
            old_name='machine_area',
            new_name='area',
        ),
    ]
