# Generated by Django 3.0.5 on 2020-04-21 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('host_management', '0028_auto_20200420_2234'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task_pool', '0004_auto_20200420_1951'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeployRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='平台名称')),
                ('deploy_time', models.DateTimeField(verbose_name='上线时间')),
                ('request_user', models.CharField(max_length=20, verbose_name='发起人')),
                ('deploy_result', models.PositiveSmallIntegerField(choices=[(1, '成功'), (2, '失败')], default=1, verbose_name='上线结果')),
                ('desc', models.CharField(blank=True, max_length=100, null=True, verbose_name='备注')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, '关闭'), (1, '开启')], default=1, verbose_name='状态')),
                ('deploy_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dep_user', to=settings.AUTH_USER_MODEL, verbose_name='处理人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dep_project', to='host_management.ProjectInfo', verbose_name='项目')),
                ('url', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dep_url', to='host_management.DomainNameResolveInfo', verbose_name='域名')),
            ],
            options={
                'verbose_name': '上线表',
                'verbose_name_plural': '上线表',
            },
        ),
    ]
