# Generated by Django 3.0.5 on 2020-04-21 08:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('task_pool', '0005_deployrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectiontaskcyclesetting',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='更新时间'),
            preserve_default=False,
        ),
    ]
