# Generated by Django 3.0.5 on 2020-04-21 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_pool', '0006_inspectiontaskcyclesetting_add_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectiontasklist',
            name='status',
            field=models.CharField(choices=[('done', '已处理'), ('pending', '未处理'), ('other', '其他')], default='pending', max_length=8, verbose_name='状态'),
        ),
    ]
