# Generated by Django 3.0.5 on 2020-04-22 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_pool', '0008_auto_20200421_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectiontasklist',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
    ]
