# Generated by Django 3.0.5 on 2020-04-24 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asset_management', '0002_auto_20200424_1827'),
        ('task_pool', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceTaskList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=20, null=True, verbose_name='创建人')),
                ('point', models.CharField(max_length=20, null=True, verbose_name='检查点')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('cycle', models.SmallIntegerField(null=True, verbose_name='任务生成周期')),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='检查内容描述')),
                ('status', models.CharField(choices=[('done', '已处理'), ('pending', '未处理'), ('other', '其他')], default='pending', max_length=8, verbose_name='状态')),
                ('result', models.CharField(max_length=50, null=True, verbose_name='检查结果')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_machine_area_list_name', to='asset_management.Area', verbose_name='设备所在区域')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_machine_name_list', to='asset_management.Machine', verbose_name='巡检设备')),
                ('operator1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_list_operator1', to=settings.AUTH_USER_MODEL, verbose_name='负责人1')),
                ('operator2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_list_operator2', to=settings.AUTH_USER_MODEL, verbose_name='负责人2')),
            ],
            options={
                'verbose_name': '巡检任务表',
                'verbose_name_plural': '巡检任务表',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceTaskCycleSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.CharField(max_length=20, null=True, verbose_name='检查点')),
                ('start_time', models.DateTimeField(null=True, verbose_name='起始时间')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='检查内容描述')),
                ('cycle', models.SmallIntegerField(null=True, verbose_name='任务生成周期')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_machine_area_name', to='asset_management.Area', verbose_name='设备所在区域')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_machine_name', to='asset_management.Machine', verbose_name='巡检设备')),
                ('operator1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_operator1', to=settings.AUTH_USER_MODEL, verbose_name='负责人1')),
                ('operator2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_operator2', to=settings.AUTH_USER_MODEL, verbose_name='负责人2')),
            ],
            options={
                'verbose_name': '巡检任务周期设定表',
                'verbose_name_plural': '巡检任务周期设定表',
            },
        ),
        migrations.CreateModel(
            name='InspectionTaskList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=20, null=True, verbose_name='创建人')),
                ('point', models.CharField(max_length=20, null=True, verbose_name='检查点')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('cycle', models.SmallIntegerField(null=True, verbose_name='任务生成周期')),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='检查内容描述')),
                ('status', models.CharField(choices=[('done', '已处理'), ('pending', '未处理'), ('other', '其他')], default='pending', max_length=8, verbose_name='状态')),
                ('result', models.CharField(max_length=50, null=True, verbose_name='检查结果')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_machine_area_list_name', to='asset_management.Area', verbose_name='设备所在区域')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_machine_name_list', to='asset_management.Machine', verbose_name='巡检设备')),
                ('operator1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspection_list_operator1', to=settings.AUTH_USER_MODEL, verbose_name='负责人1')),
                ('operator2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspection_list_operator2', to=settings.AUTH_USER_MODEL, verbose_name='负责人2')),
            ],
            options={
                'verbose_name': '巡检任务表',
                'verbose_name_plural': '巡检任务表',
            },
        ),
        migrations.CreateModel(
            name='InspectionTaskCycleSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.CharField(max_length=20, null=True, verbose_name='检查点')),
                ('start_time', models.DateTimeField(null=True, verbose_name='起始时间')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='检查内容描述')),
                ('cycle', models.SmallIntegerField(null=True, verbose_name='任务生成周期')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_machine_area_name', to='asset_management.Area', verbose_name='设备所在区域')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_machine_name', to='asset_management.Machine', verbose_name='巡检设备')),
                ('operator1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_operator1', to=settings.AUTH_USER_MODEL, verbose_name='负责人1')),
                ('operator2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspection_operator2', to=settings.AUTH_USER_MODEL, verbose_name='负责人2')),
            ],
            options={
                'verbose_name': '巡检任务周期设定表',
                'verbose_name_plural': '巡检任务周期设定表',
            },
        ),
    ]
